name: Dynamic S3 Bucket Deployment

on:
  push:
    paths:
      - 'list-bucket/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Extract Folder Names
      id: extract
      run: |
        FOLDER_NAMES=$(find list-bucket/* -maxdepth 0 -type d -exec basename {} \;)
        echo "${FOLDER_NAMES}" >> $GITHUB_ENV

    - name: Create S3 Buckets
      run: |
        IFS=$'\n' # Set Internal Field Separator (IFS) to newline
        for BUCKET_NAME in ${{ env.FOLDER_NAMES }}; do
          aws s3api create-bucket --bucket $BUCKET_NAME --region your-region
        done
